<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJVE3XGX\appAppKernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJVE3XGX/appAppKernelProdContainer.php') {
    touch(__DIR__.'/ContainerJVE3XGX.legacy');

    return;
}

if (!\class_exists(appAppKernelProdContainer::class, false)) {
    \class_alias(\ContainerJVE3XGX\appAppKernelProdContainer::class, appAppKernelProdContainer::class, false);
}

return new \ContainerJVE3XGX\appAppKernelProdContainer([
    'container.build_hash' => 'JVE3XGX',
    'container.build_id' => '9e0e41da',
    'container.build_time' => 1686732843,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJVE3XGX');
