<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKe8myHb\appAppKernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKe8myHb/appAppKernelProdContainer.php') {
    touch(__DIR__.'/ContainerKe8myHb.legacy');

    return;
}

if (!\class_exists(appAppKernelProdContainer::class, false)) {
    \class_alias(\ContainerKe8myHb\appAppKernelProdContainer::class, appAppKernelProdContainer::class, false);
}

return new \ContainerKe8myHb\appAppKernelProdContainer([
    'container.build_hash' => 'Ke8myHb',
    'container.build_id' => '4b0345fb',
    'container.build_time' => 1686732819,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerKe8myHb');
